#!/bin/bash
#SBATCH --partition=standard
#SBATCH --account=krasny1

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=4000m
#SBATCH --time=00:01:00

#SBATCH --job-name="testing"
#SBATCH --output="testing--%j.%N.out"



srun -n 1 random_cube_cpu example.in