#!/bin/bash


TREETYPE=1
THETA=0.8
ORDER=7
CLUSTERSIZE=100
BATCHSIZE=100
KAPPA=0.5

COMPAREDIRECT=1

for N in 2500 
do
    for NP in 4
    do
        for KERNEL in coulomb yukawa coulomb_SS yukawa_SS
        #for KERNEL in yukawa_SS coulomb_SS
        do
            echo $NP
            echo $KERNEL
            mpirun -n ${NP} zoltan_example_cpu $N $ORDER $THETA $CLUSTERSIZE $BATCHSIZE $KERNEL $KAPPA $TREETYPE $COMPAREDIRECT 
        done
    done   
done      
