#!/bin/bash


TREETYPE=1
THETA=0.8
ORDER=7
CLUSTERSIZE=100
BATCHSIZE=100
KAPPA=0.5

APPROXIMATIONNAME=Lagrange
COMPAREDIRECT=1

for N in 2500 
do
    for NP in 4
    do
        for KERNEL in coulomb yukawa 
        do
            for SINGULARITYHANDLING in skipping subtraction
            do
                echo $NP
                echo $KERNEL
                echo $SINGULARITYHANDLING
                mpirun -n ${NP} zoltan_example_cpu $N $ORDER $THETA $CLUSTERSIZE $BATCHSIZE $KERNEL $KAPPA $SINGULARITYHANDLING $APPROXIMATIONNAME $TREETYPE $COMPAREDIRECT 
            done
        done
    done   
done      
