#!/bin/bash



THETA=0.8
ORDER=6
CLUSTERSIZE=500
BATCHSIZE=500
KERNEL=0
KAPPA=0.0


for N in 100000 
do
	for NX in 1 
	do
		for NY in 1
		do
			for NZ in 1
			do
				NP=$(($NX * $NY * $NZ))
				echo $NP
				SOURCES=/scratch/krasny_fluxg/njvaughn/random/S${N}_${NX}x_${NY}y_${NZ}z.bin
				TARGETS=/scratch/krasny_fluxg/njvaughn/random/T${N}_${NX}x_${NY}y_${NZ}z.bin
				OFFSETS=/scratch/krasny_fluxg/njvaughn/random/offsets${N}_${NX}x_${NY}y_${NZ}z.bin
				DIRECT=/scratch/krasny_fluxg/njvaughn/random/direct_gpu_${N}.bin
				OUTPUT=/scratch/krasny_fluxg/njvaughn/random/tree_gpu_${N}.csv
				mpirun -n ${NP} direct-distributed-gpu $SOURCES $TARGETS $DIRECT $OUTPUT $N $N $KAPPA $KERNEL 
				mpirun -n ${NP} tree-distributed-gpu $SOURCES $TARGETS $OFFSETS $OFFSETS $DIRECT $OUTPUT $N $N $THETA $ORDER $CLUSTERSIZE $BATCHSIZE $KERNEL $KAPPA 
			done
		done   
	done  
done    
