#!/bin/bash


TREETYPE=1
THETA=0.7
ORDER=8
CLUSTERSIZE=1000
BATCHSIZE=1000
KAPPA=0.01

APPROXIMATIONNAME=lagrange
COMPAREDIRECT=1

NP=1
N=79576
N=21952
SOURCES=/Users/nathanvaughn/Documents/GitHub/BaryTree/examplesOxygenAtom/S${N}.bin
TARGETS=/Users/nathanvaughn/Documents/GitHub/BaryTree/examplesOxygenAtom/T${N}.bin
DIRECT=/Users/nathanvaughn/Desktop/randomPoints/SS_KI_direct_gpu_${N}.bin
OUTPUT=/Users/nathanvaughn/Desktop/randomPoints/SS_KI_tree_gpu_${N}.csv
OFFSETS=/Users/nathanvaughn/Desktop/randomPoints/offsets100000_${1}x_${1}y_${1}z.bin
for ORDER in 6 
do
    for APPROXIMATIONNAME in lagrange #hermite
    do
        for KERNEL in coulomb #yukawa #coulomb 
        do
            for SINGULARITYHANDLING in skipping #subtraction #skipping 
            do
                echo
                echo 
                echo $NP
                echo $KERNEL
                echo $SINGULARITYHANDLING
                echo $APPROXIMATIONNAME
                echo
                mpirun -n ${NP} direct-distributed-cpu $SOURCES $TARGETS $DIRECT $OUTPUT $N $N $KAPPA $KERNEL
                mpirun -n ${NP} tree-distributed-cpu $SOURCES $TARGETS $OFFSETS $OFFSETS $DIRECT $OUTPUT $N $N $THETA $ORDER $CLUSTERSIZE $BATCHSIZE $KERNEL $KAPPA $APPROXIMATIONNAME
                
                #mpirun -n ${NP} zoltan_example_cpu $N $ORDER $THETA $CLUSTERSIZE $BATCHSIZE $KERNEL $KAPPA $SINGULARITYHANDLING $APPROXIMATIONNAME $TREETYPE $COMPAREDIRECT 
            done
        done
    done   
done      
