#!/bin/bash
#SBATCH --partition=standard
#SBATCH --account=krasny1

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=4g
#SBATCH --time=00:10:00

#SBATCH --job-name="testing"
#SBATCH --output="testing--%j.%N.out"



TREETYPE=1
THETA=0.8
CLUSTERSIZE=500
BATCHSIZE=500
NUMBEROFKERNELPARAMETERS=1
KERNELPARAMETER1=0.5

APPROXIMATIONNAME=lagrange
COMPAREDIRECT=1
VERBOSITY=0
SIZECHECKFACTOR=1.0
COMPAREEVERY=100

NP=$1
N=10000
for ORDER in 6 
do
    for VERBOSITY in 1
    do
        for KERNEL in coulomb 
        do
            for SINGULARITYHANDLING in skipping #subtraction 
            do
                echo
                echo 
                echo $NP
                echo $N
                echo $KERNEL
                echo $SINGULARITYHANDLING
                echo $APPROXIMATIONNAME
                echo
                srun -n 1 zoltan_example_cpu $N $ORDER $THETA $CLUSTERSIZE $BATCHSIZE $KERNEL $SINGULARITYHANDLING $APPROXIMATIONNAME $TREETYPE $SIZECHECKFACTOR \
                                                 $COMPAREDIRECT $VERBOSITY $COMPAREEVERY $NUMBEROFKERNELPARAMETERS $KERNELPARAMETER1
            done
        done
    done   
done      
