#!/bin/bash

for N in 10000 100000 1000000 10000000
do
	for nx in 7 
	do
		for ny in 7
		do
			for nz in 5
			do
    
				#python pointSorter_nxnynz.py $N $n 3 2 '/gpfs/wolf/proj-shared/gen135/BaryTree/randomPoints/'    
				python pointSorter_nxnynz.py $N $nx $ny $nz '/scratch/krasny_root/krasny/njvaughn/randomPoints/' 
			done
		done   
	done  
done    
