#!/bin/bash


TREETYPE=1
THETA=0.8
CLUSTERSIZE=2000
BATCHSIZE=2000
KAPPA=0.5

APPROXIMATIONNAME=lagrange
COMPAREDIRECT=1
VERBOSITY=0

NP=$1

for ORDER in 7
do
    #for SIZECHECKFACTOR in 0.6 0.8 1.0 1.2 1.4 1.6 1.8 2.0 10000000
    for SIZECHECKFACTOR in 0 0.5 1 1.5 2 4
    do
        for KERNEL in coulomb  
        do
            for SINGULARITYHANDLING in subtraction  
            do
                N=$((200000/$NP)) 
                echo
                echo 
                echo $NP
                echo $N
                echo SIZECHECKFACTOR = $SIZECHECKFACTOR
                echo $KERNEL
                echo $SINGULARITYHANDLING
                echo $APPROXIMATIONNAME
                echo
                mpirun -n $NP zoltan_example_cpu $N $ORDER $THETA $CLUSTERSIZE $BATCHSIZE $KERNEL $KAPPA $SINGULARITYHANDLING $APPROXIMATIONNAME $TREETYPE $SIZECHECKFACTOR $COMPAREDIRECT $VERBOSITY
            done
        done
    done   
done      
