#!/bin/bash


N=79567
N=21952
SOURCES=../examplesOxygenAtom/S$N.bin
TARGETS=../examplesOxygenAtom/T$N.bin
DIRECTSUM=../examplesOxygenAtom/ex_st79567_coulomb.bin
DS_CSV=../examplesOxygenAtom/local_coulomb.csv  

OUTFILE=../examplesOxygenAtom/out.csv
THETA=0.9
ORDER=8
TREETYPE=1
MAXPARNODE=1000
KAPPA=0.0
POTENTIALTYPE=0
PFLAG=0
SFLAG=1
DFLAG=0
BATCHSIZE=1000
NUMDEVICES=0
NUMTHREADS=6

../bin/direct.exe   $SOURCES $TARGETS $DIRECTSUM $DS_CSV $N $N $KAPPA $POTENTIALTYPE $NUMDEVICES $NUMTHREADS
../bin/tree.exe   $SOURCES $TARGETS $DIRECTSUM $OUTFILE $N $N $THETA $ORDER $TREETYPE $MAXPARNODE $KAPPA $POTENTIALTYPE $PFLAG $SFLAG $DFLAG $BATCHSIZE $NUMDEVICES $NUMTHREADS